name: Deploy to S3

#Define when this workflow will run 
on: 
  push: 
    branches: 
      - master

#Deploy front end code (Define the deployment job)
jobs:
  deploy: 
    #Specify the enviornment for the job to run in 
    runs-on: ubuntu-latest 

    #Define steps in the job
    steps: 
      #Check out the code from the repository 
      - name: Checkout repository 
        uses: actions/checkout@v4

      #Sync the files to S3. Use ${{to create a secret key within the brackets}} 
      - name: Sync files to S3
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude ".git*"
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      #Invalidate the CloudFront cache so any index,html updates can be seen immediately 
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1